var recipeArray= [];
var indexRecipeArray=[];
var ingredientsArray=[];
var ingredientWordList=[];
var itemIngredientsArray=[];
var ingredient=[];
var descriptionArray=[];
var ustensilArray=[];
var appareilArray=[];
var keyWordsArray =[];
var correspondantWords =[];
var recipeFilterArray=[];
var recipeResult=[]
var ingredientsFilterArray=[];
var appliancesFilterArray=[];
var ustensilsFilterArray=[];
var searchBar = document.getElementById("searchbar");
var searchFilterIng = document.getElementById("tags_ing");
var searchFilterApp = document.getElementById("tags_app");
var searchFilterUst = document.getElementById("tags_ust");
// var recipeLoad=recipes
var applianceArray=[];
var tagIngredientSearch =[];
var recipeResultFilter = [];
