var recipeArray= [];
var indexRecipeArray=[];
var ingredientsArray=[];
var ingredientWordList=[];
var itemIngredientsArray=[];
var ingredient=[];
var descriptionArray=[];
var ustensilArray=[];
var appareilArray=[];
var keyWordsArray =[];
var correspondantWords =[];
var recipeFilterArray=[];
var recipeResult=[]
var ingredientsFilterArray=[];
var appliancesFilterArray=[];
var ustensilsFilterArray=[];
var ingredientsFilterArray=[];
var ustensilsFilterArray=[];
var appliancesFilterArray=[];
var searchBar = document.getElementById("searchbar");
var recipeLoad=recipes